import type { Lang } from './config';

const copy:Record<string,Partial<Record<Lang,{title:string;description:string}>>>={
 'air':{ru:{title:'AIR — анализ взаимозависимостей',description:'Модель анализа межсекторных зависимостей, путей распространения риска и критических точек.'},es:{title:'AIR — análisis de interdependencias',description:'Marco para analizar dependencias intersectoriales, propagación del riesgo y puntos críticos.'},ca:{title:'AIR — anàlisi d’interdependències',description:'Marc per analitzar dependències intersectorials, propagació del risc i punts crítics.'},fr:{title:'AIR — analyse des interdépendances',description:'Cadre d’analyse des dépendances intersectorielles, de la propagation du risque et des points critiques.'},de:{title:'AIR — Interdependenzanalyse',description:'Rahmen zur Analyse sektorübergreifender Abhängigkeiten, Risikopropagation und kritischer Punkte.'},it:{title:'AIR — analisi delle interdipendenze',description:'Quadro per analizzare dipendenze intersettoriali, propagazione del rischio e punti critici.'},pt:{title:'AIR — análise de interdependências',description:'Estrutura para analisar dependências intersetoriais, propagação de risco e pontos críticos.'}},
 'dss':{ru:{title:'DSS — Decision Security System',description:'Базовая рамка проверки безопасности, доказательности и исполнимости стратегического решения.'},es:{title:'DSS — Decision Security System',description:'Marco central para verificar seguridad, evidencia y ejecutabilidad de una decisión estratégica.'},ca:{title:'DSS — Decision Security System',description:'Marc central per verificar seguretat, evidència i executabilitat d’una decisió estratègica.'},fr:{title:'DSS — Decision Security System',description:'Cadre central pour vérifier la sécurité, les preuves et l’exécutabilité d’une décision stratégique.'},de:{title:'DSS — Decision Security System',description:'Kernrahmen zur Prüfung von Sicherheit, Evidenz und Umsetzbarkeit einer strategischen Entscheidung.'},it:{title:'DSS — Decision Security System',description:'Quadro centrale per verificare sicurezza, evidenze ed eseguibilità di una decisione strategica.'},pt:{title:'DSS — Decision Security System',description:'Estrutura central para verificar segurança, evidência e executabilidade de uma decisão estratégica.'}},
 'scm':{ru:{title:'SCM — модель системной согласованности',description:'Диагностика структурной устойчивости по ключевым осям безопасности.'},es:{title:'SCM — modelo de coherencia del sistema',description:'Diagnóstico de resiliencia estructural a través de ejes clave de seguridad.'},ca:{title:'SCM — model de coherència del sistema',description:'Diagnòstic de resiliència estructural a través d’eixos clau de seguretat.'},fr:{title:'SCM — modèle de cohérence du système',description:'Diagnostic de résilience structurelle sur les principaux axes de sécurité.'},de:{title:'SCM — Systemkohärenzmodell',description:'Diagnose struktureller Resilienz über zentrale Sicherheitsachsen.'},it:{title:'SCM — modello di coerenza del sistema',description:'Diagnosi della resilienza strutturale attraverso i principali assi di sicurezza.'},pt:{title:'SCM — modelo de coerência do sistema',description:'Diagnóstico de resiliência estrutural através dos principais eixos de segurança.'}},
 'evidence-registry':{ru:{title:'Evidence Registry — реестр доказательной базы',description:'Контрольный слой, разделяющий подтверждённые факты, внутренние предпосылки, расчёты и экспертную интерпретацию.'},es:{title:'Evidence Registry — registro de evidencia',description:'Capa de control que separa hechos respaldados por fuentes, supuestos internos, cálculos e interpretación experta.'},ca:{title:'Evidence Registry — registre d’evidència',description:'Capa de control que separa fets sustentats per fonts, supòsits interns, càlculs i interpretació experta.'},fr:{title:'Evidence Registry — registre des éléments probants',description:'Couche de contrôle séparant les faits sourcés, les hypothèses internes, les calculs et l’interprétation experte.'},de:{title:'Evidence Registry — Evidenzregister',description:'Kontrollschicht zur Trennung belegter Fakten, interner Annahmen, Berechnungen und Experteninterpretation.'},it:{title:'Evidence Registry — registro delle evidenze',description:'Livello di controllo che separa fatti supportati da fonti, ipotesi interne, calcoli e interpretazione esperta.'},pt:{title:'Evidence Registry — registo de evidência',description:'Camada de controlo que separa factos sustentados por fontes, pressupostos internos, cálculos e interpretação especializada.'}},
 'scenario-stress-testing':{ru:{title:'Scenario Stress-Test — сценарный стресс-тест',description:'Проверка решений через альтернативные будущие условия, шоки и отказы зависимостей.'},es:{title:'Scenario Stress-Test — prueba de estrés de escenarios',description:'Prueba de decisiones ante condiciones futuras alternativas, shocks y fallos de dependencias.'},ca:{title:'Scenario Stress-Test — prova d’estrès d’escenaris',description:'Prova de decisions davant condicions futures alternatives, xocs i fallades de dependències.'},fr:{title:'Scenario Stress-Test — test de résistance des scénarios',description:'Test des décisions face à des futurs alternatifs, chocs et défaillances de dépendances.'},de:{title:'Scenario Stress-Test — Szenario-Stresstest',description:'Prüfung von Entscheidungen gegen alternative Zukunftslagen, Schocks und Abhängigkeitsausfälle.'},it:{title:'Scenario Stress-Test — stress test di scenario',description:'Verifica delle decisioni rispetto a futuri alternativi, shock e fallimenti delle dipendenze.'},pt:{title:'Scenario Stress-Test — teste de stress de cenários',description:'Teste de decisões perante futuros alternativos, choques e falhas de dependências.'}},
 'family-business':{ru:{title:'Decision Security для семейного бизнеса',description:'Исследовательское направление, где взаимодействуют владение, корпоративное управление, преемственность, капитал и операционные зависимости.'},es:{title:'Decision Security para la empresa familiar',description:'Área de investigación donde interactúan propiedad, gobernanza, sucesión, capital y dependencias operativas.'},ca:{title:'Decision Security per a l’empresa familiar',description:'Àrea de recerca on interactuen propietat, governança, successió, capital i dependències operatives.'},fr:{title:'Decision Security pour l’entreprise familiale',description:'Domaine de recherche où interagissent propriété, gouvernance, succession, capital et dépendances opérationnelles.'},de:{title:'Decision Security für Familienunternehmen',description:'Forschungsfeld, in dem Eigentum, Governance, Nachfolge, Kapital und operative Abhängigkeiten zusammenwirken.'},it:{title:'Decision Security per l’impresa familiare',description:'Area di ricerca in cui interagiscono proprietà, governance, successione, capitale e dipendenze operative.'},pt:{title:'Decision Security para empresas familiares',description:'Área de investigação onde interagem propriedade, governação, sucessão, capital e dependências operacionais.'}},
 'strategic-decision-audit':{ru:{title:'Аудит стратегических решений — Strategic Decision Audit',description:'Структурированный аудит логики стратегического решения, доказательств, зависимостей, сценариев и готовности к реализации.'},es:{title:'Auditoría de decisiones estratégicas — Strategic Decision Audit',description:'Auditoría estructurada de la lógica de una decisión estratégica, su evidencia, dependencias, escenarios y preparación para la implementación.'},ca:{title:'Auditoria de decisions estratègiques — Strategic Decision Audit',description:'Auditoria estructurada de la lògica d’una decisió estratègica, l’evidència, les dependències, els escenaris i la preparació per a la implementació.'},fr:{title:'Audit des décisions stratégiques — Strategic Decision Audit',description:'Audit structuré de la logique d’une décision stratégique, des preuves, des dépendances, des scénarios et de la préparation à la mise en œuvre.'},de:{title:'Audit strategischer Entscheidungen — Strategic Decision Audit',description:'Strukturiertes Audit der Logik strategischer Entscheidungen, Evidenz, Abhängigkeiten, Szenarien und Umsetzungsbereitschaft.'},it:{title:'Audit delle decisioni strategiche — Strategic Decision Audit',description:'Audit strutturato della logica di una decisione strategica, delle evidenze, delle dipendenze, degli scenari e della preparazione all’implementazione.'},pt:{title:'Auditoria de decisões estratégicas — Strategic Decision Audit',description:'Auditoria estruturada da lógica de uma decisão estratégica, da evidência, das dependências, dos cenários e da preparação para a implementação.'}},
 'decision-security-research-program':{ru:{title:'Программа исследований Decision Security',description:'Исследовательская программа по устойчивости стратегических решений, качеству доказательной базы и системным взаимозависимостям.'},es:{title:'Programa de investigación Decision Security',description:'Agenda de investigación sobre resiliencia de decisiones estratégicas, calidad de la evidencia e interdependencias del sistema.'},ca:{title:'Programa de recerca Decision Security',description:'Agenda de recerca sobre resiliència de les decisions estratègiques, qualitat de l’evidència i interdependències del sistema.'},fr:{title:'Programme de recherche Decision Security',description:'Programme de recherche sur la résilience des décisions stratégiques, la qualité des preuves et les interdépendances du système.'},de:{title:'Decision-Security-Forschungsprogramm',description:'Forschungsagenda zu Resilienz strategischer Entscheidungen, Evidenzqualität und Systeminterdependenzen.'},it:{title:'Programma di ricerca Decision Security',description:'Agenda di ricerca sulla resilienza delle decisioni strategiche, la qualità delle evidenze e le interdipendenze del sistema.'},pt:{title:'Programa de investigação Decision Security',description:'Agenda de investigação sobre resiliência das decisões estratégicas, qualidade da evidência e interdependências do sistema.'}}
};

const typeCopy:Record<string,Partial<Record<Lang,string>>>={
  methodology:{ru:'МЕТОДОЛОГИЯ',es:'METODOLOGÍA',ca:'METODOLOGIA',fr:'MÉTHODOLOGIE',de:'METHODIK',it:'METODOLOGIA',pt:'METODOLOGIA'},
  research:{ru:'ИССЛЕДОВАНИЯ',es:'INVESTIGACIÓN',ca:'RECERCA',fr:'RECHERCHE',de:'FORSCHUNG',it:'RICERCA',pt:'INVESTIGAÇÃO'},
  evidence:{ru:'ДОКАЗАТЕЛЬСТВА',es:'EVIDENCIA',ca:'EVIDÈNCIA',fr:'PREUVES',de:'EVIDENZ',it:'EVIDENZE',pt:'EVIDÊNCIA'},
  industry:{ru:'ОТРАСЛЬ',es:'SECTOR',ca:'SECTOR',fr:'SECTEUR',de:'BRANCHE',it:'SETTORE',pt:'SETOR'},
  product:{ru:'ПРОДУКТ',es:'PRODUCTO',ca:'PRODUCTE',fr:'PRODUIT',de:'PRODUKT',it:'PRODOTTO',pt:'PRODUTO'}
};

const tagCopy:Record<string,Partial<Record<Lang,string>>>={
  'air':{ru:'AIR'},
  'interdependency':{ru:'ВЗАИМОЗАВИСИМОСТИ',es:'INTERDEPENDENCIAS',ca:'INTERDEPENDÈNCIES',fr:'INTERDÉPENDANCES',de:'INTERDEPENDENZEN',it:'INTERDIPENDENZE',pt:'INTERDEPENDÊNCIAS'},
  'dss':{ru:'DSS'},
  'decision security':{ru:'DECISION SECURITY'},
  'evidence':{ru:'ДОКАЗАТЕЛЬСТВА',es:'EVIDENCIA',ca:'EVIDÈNCIA',fr:'PREUVES',de:'EVIDENZ',it:'EVIDENZE',pt:'EVIDÊNCIA'},
  'sources':{ru:'ИСТОЧНИКИ',es:'FUENTES',ca:'FONTS',fr:'SOURCES',de:'QUELLEN',it:'FONTI',pt:'FONTES'},
  'family business':{ru:'СЕМЕЙНЫЙ БИЗНЕС',es:'EMPRESA FAMILIAR',ca:'EMPRESA FAMILIAR',fr:'ENTREPRISE FAMILIALE',de:'FAMILIENUNTERNEHMEN',it:'IMPRESA FAMILIARE',pt:'EMPRESA FAMILIAR'},
  'governance':{ru:'УПРАВЛЕНИЕ',es:'GOBERNANZA',ca:'GOVERNANÇA',fr:'GOUVERNANCE',de:'GOVERNANCE',it:'GOVERNANCE',pt:'GOVERNAÇÃO'},
  'scenario':{ru:'СЦЕНАРИИ',es:'ESCENARIOS',ca:'ESCENARIS',fr:'SCÉNARIOS',de:'SZENARIEN',it:'SCENARI',pt:'CENÁRIOS'},
  'stress testing':{ru:'СТРЕСС-ТЕСТ',es:'PRUEBA DE ESTRÉS',ca:'PROVA D’ESTRÈS',fr:'TEST DE RÉSISTANCE',de:'STRESSTEST',it:'STRESS TEST',pt:'TESTE DE STRESS'},
  'decision audit':{ru:'АУДИТ РЕШЕНИЙ',es:'AUDITORÍA DE DECISIONES',ca:'AUDITORIA DE DECISIONS',fr:'AUDIT DES DÉCISIONS',de:'ENTSCHEIDUNGSAUDIT',it:'AUDIT DELLE DECISIONI',pt:'AUDITORIA DE DECISÕES'},
  'strategy':{ru:'СТРАТЕГИЯ',es:'ESTRATEGIA',ca:'ESTRATÈGIA',fr:'STRATÉGIE',de:'STRATEGIE',it:'STRATEGIA',pt:'ESTRATÉGIA'},
  'research':{ru:'ИССЛЕДОВАНИЯ',es:'INVESTIGACIÓN',ca:'RECERCA',fr:'RECHERCHE',de:'FORSCHUNG',it:'RICERCA',pt:'INVESTIGAÇÃO'}
};

export function localizeKnowledge(id:string,lang:Lang,title:string,description:string){return copy[id]?.[lang] ?? {title,description};}
export function localizeKnowledgeType(type:string,lang:Lang){return typeCopy[type]?.[lang] ?? type.toUpperCase();}
export function localizeKnowledgeTag(tag:string,lang:Lang){return tagCopy[tag.toLowerCase()]?.[lang] ?? tag.toUpperCase();}
