import type { Lang } from './config';
import type { MethodologyArticle } from './methodology-content';

type LocalizedArticles = Partial<Record<Lang, MethodologyArticle>>;

/**
 * TAMVER Research & Knowledge Translation Synchronization v0.8.6.1.
 * Source of meaning: expanded canonical English articles in src/content/knowledge.
 * Controlled TAMVER identifiers remain unchanged where they function as product,
 * methodology or program names. No new quantitative claims are introduced.
 */
export const researchKnowledgeContent: Record<string, LocalizedArticles> = {
  'family-business': {
    ru:{sections:[
      {heading:'Фокус исследования',paragraphs:['Это направление изучает стратегические решения в семейном бизнесе через управление решениями, взаимозависимости и устойчивость к сценариям.']},
      {heading:'Почему семейному бизнесу нужен отдельный подход',paragraphs:['В семейной компании одно стратегическое решение одновременно затрагивает владение, операционный контроль, семейное управление, преемственность, структуру капитала, регуляторные риски, репутацию и отношения между ветвями семьи. Решение, привлекательное в одной плоскости, может создавать уязвимость в другой.','Decision Security рассматривает семейное предприятие как связанную систему решений, где последствия для бизнеса и собственников должны оцениваться совместно.']},
      {heading:'Решения с высокой ценой ошибки',bullets:['преемственность и передача контроля;','продажа бизнеса или значительной доли;','приобретения и крупные капитальные вложения;','выход в новую страну, рынок или регулируемый сектор;','реструктуризация владения или семейного холдинга;','релокация или смена юрисдикции;','создание или перестройка family office;','крупная цифровая или AI-трансформация;','решения с существенной регуляторной, репутационной или семейно-конфликтной экспозицией.']},
      {heading:'Перспектива Decision Security',paragraphs:['Ключевой вопрос состоит не только в том, законна ли сделка или финансово привлекательна стратегия. Проверяется, остаётся ли решение обоснованным, если совместно рассмотреть предпосылки, доказательства, зависимости, альтернативные сценарии и условия реализации.','TAMVER отделяет независимую верификацию решения от его исполнения. Юридические, налоговые, инвестиционные и транзакционные советники могут продолжать реализацию, а Decision Security проверяет решение до принятия обязательств.']},
      {heading:'Исследовательские измерения',numbered:['Необратимость — насколько трудно и дорого отменить решение.','Экспозиция капитала — какая часть семейного капитала или операционной способности находится под риском.','Экспозиция семейного управления — затрагиваются ли разные ветви, поколения или права контроля.','Регуляторная и трансграничная экспозиция — зависит ли решение от налоговых, AML, substance, отчётных или юрисдикционных условий.','Стимулы советников — получают ли участники исполнения выгоду от того, что сделка состоится.','Репутационная и операционная экспозиция — может ли решение повлиять на непрерывность, доверие, позицию на рынке или критические зависимости.']},
      {heading:'Типовые методы TAMVER',bullets:['DSS — проверка качества решения, доказательности и готовности к реализации;','AIR — карта межсистемных и межсекторных зависимостей;','Scenario Stress-Test — проверка альтернативных будущих условий и отказов;','SCM — оценка устойчивости структуры, которая должна реализовать решение;','Evidence Registry — разделение подтверждённых фактов, предпосылок, расчётов и экспертной интерпретации.']},
      {heading:'Правило публикации',paragraphs:['Эта страница определяет исследовательскую рамку. Количественные рыночные утверждения, выводы по юрисдикциям и кейсам публикуются только после сопоставления с доказательной базой и прохождения процедуры публикации TAMVER.']}
    ]},
    es:{sections:[
      {heading:'Enfoque de investigación',paragraphs:['Esta área estudia las decisiones estratégicas en empresas familiares mediante la gobernanza de decisiones, las interdependencias y la resiliencia frente a escenarios.']},
      {heading:'Por qué la empresa familiar requiere una perspectiva específica',paragraphs:['En una empresa familiar, una decisión estratégica puede afectar simultáneamente a la propiedad, el control operativo, la gobernanza familiar, la sucesión, la estructura de capital, la exposición regulatoria, la reputación y las relaciones entre ramas familiares. Una decisión atractiva en una dimensión puede crear fragilidad en otra.','Decision Security trata a la empresa familiar como un sistema de decisiones conectado en el que deben evaluarse conjuntamente las consecuencias empresariales y patrimoniales.']},
      {heading:'Decisiones de alto impacto',bullets:['sucesión y transferencia de control;','venta del negocio o de una participación significativa;','adquisiciones y grandes inversiones de capital;','entrada en un nuevo país, mercado o sector regulado;','reestructuración de la propiedad o del holding familiar;','relocalización o cambio de jurisdicción;','creación o rediseño de un family office;','gran transformación digital o de IA;','decisiones con exposición regulatoria, reputacional o de conflicto familiar material.']},
      {heading:'Perspectiva de Decision Security',paragraphs:['La cuestión central no es solo si una operación es legalmente posible o financieramente atractiva. Se analiza si la decisión sigue siendo defendible cuando se examinan conjuntamente sus supuestos, evidencia, dependencias, escenarios alternativos y condiciones de implementación.','TAMVER separa la verificación independiente de la ejecución. Los asesores legales, fiscales, de inversión y transacción pueden seguir ejecutando mientras Decision Security examina la decisión antes del compromiso.']},
      {heading:'Dimensiones de investigación',numbered:['Irreversibilidad — dificultad y coste de revertir la decisión.','Exposición de capital — parte del patrimonio familiar o capacidad operativa puesta en riesgo.','Exposición de gobernanza familiar — ramas, generaciones o derechos de control afectados.','Exposición regulatoria y transfronteriza — dependencia de condiciones fiscales, AML, substance, reporting o jurisdicción.','Incentivos de los asesores — si los participantes en la ejecución se benefician de que la operación avance.','Exposición reputacional y operativa — impacto potencial en continuidad, confianza, posición de mercado o dependencias críticas.']},
      {heading:'Métodos TAMVER habituales',bullets:['DSS para calidad de decisión, evidencia y preparación para la implementación;','AIR para mapear dependencias entre sistemas y sectores;','Scenario Stress-Test para futuros alternativos y condiciones de fallo;','SCM para examinar la resiliencia de la estructura que debe soportar la decisión;','Evidence Registry para separar hechos respaldados por fuentes, supuestos, cálculos e interpretación experta.']},
      {heading:'Regla de publicación',paragraphs:['Esta página define el marco de investigación. Las afirmaciones cuantitativas de mercado, conclusiones jurisdiccionales y hallazgos de casos solo deben publicarse cuando estén vinculados a evidencia y aprobados mediante el proceso de publicación TAMVER.']}
    ]},
    ca:{sections:[
      {heading:'Enfocament de recerca',paragraphs:['Aquesta àrea estudia les decisions estratègiques en empreses familiars mitjançant la governança de decisions, les interdependències i la resiliència davant d’escenaris.']},
      {heading:'Per què l’empresa familiar requereix una perspectiva específica',paragraphs:['En una empresa familiar, una decisió estratègica pot afectar alhora la propietat, el control operatiu, la governança familiar, la successió, l’estructura de capital, l’exposició reguladora, la reputació i les relacions entre branques familiars. Una decisió atractiva en una dimensió pot crear fragilitat en una altra.','Decision Security tracta l’empresa familiar com un sistema de decisions connectat en què les conseqüències empresarials i patrimonials s’han d’avaluar conjuntament.']},
      {heading:'Decisions d’alt impacte',bullets:['successió i transferència de control;','venda del negoci o d’una participació significativa;','adquisicions i grans inversions de capital;','entrada en un nou país, mercat o sector regulat;','reestructuració de la propietat o del holding familiar;','relocalització o canvi de jurisdicció;','creació o redisseny d’un family office;','gran transformació digital o d’IA;','decisions amb exposició reguladora, reputacional o de conflicte familiar material.']},
      {heading:'Perspectiva de Decision Security',paragraphs:['La qüestió central no és només si una operació és legalment possible o financerament atractiva. S’analitza si la decisió continua sent defensable quan s’examinen conjuntament els supòsits, l’evidència, les dependències, els escenaris alternatius i les condicions d’implementació.','TAMVER separa la verificació independent de l’execució. Els assessors legals, fiscals, d’inversió i transacció poden continuar executant mentre Decision Security examina la decisió abans del compromís.']},
      {heading:'Dimensions de recerca',numbered:['Irreversibilitat — dificultat i cost de revertir la decisió.','Exposició de capital — part del patrimoni familiar o capacitat operativa posada en risc.','Exposició de governança familiar — branques, generacions o drets de control afectats.','Exposició reguladora i transfronterera — dependència de condicions fiscals, AML, substance, reporting o jurisdicció.','Incentius dels assessors — si els participants en l’execució es beneficien que l’operació avanci.','Exposició reputacional i operativa — impacte potencial en continuïtat, confiança, posició de mercat o dependències crítiques.']},
      {heading:'Mètodes TAMVER habituals',bullets:['DSS per a qualitat de decisió, evidència i preparació per a la implementació;','AIR per cartografiar dependències entre sistemes i sectors;','Scenario Stress-Test per a futurs alternatius i condicions de fallada;','SCM per examinar la resiliència de l’estructura que ha de sostenir la decisió;','Evidence Registry per separar fets sustentats per fonts, supòsits, càlculs i interpretació experta.']},
      {heading:'Regla de publicació',paragraphs:['Aquesta pàgina defineix el marc de recerca. Les afirmacions quantitatives de mercat, conclusions jurisdiccionals i resultats de casos només s’han de publicar quan estiguin vinculats a evidència i aprovats mitjançant el procés de publicació TAMVER.']}
    ]},
    fr:{sections:[
      {heading:'Axe de recherche',paragraphs:['Ce domaine étudie les décisions stratégiques dans les entreprises familiales au moyen de la gouvernance des décisions, des interdépendances et de la résilience aux scénarios.']},
      {heading:'Pourquoi l’entreprise familiale exige une approche spécifique',paragraphs:['Dans une entreprise familiale, une décision stratégique peut affecter simultanément la propriété, le contrôle opérationnel, la gouvernance familiale, la succession, la structure du capital, l’exposition réglementaire, la réputation et les relations entre branches familiales. Une décision attractive sur un axe peut créer de la fragilité sur un autre.','Decision Security considère l’entreprise familiale comme un système de décision connecté dans lequel les conséquences pour l’entreprise et les propriétaires doivent être évaluées ensemble.']},
      {heading:'Décisions à fort enjeu',bullets:['succession et transfert du contrôle ;','vente de l’entreprise ou d’une participation significative ;','acquisitions et investissements majeurs ;','entrée dans un nouveau pays, marché ou secteur réglementé ;','restructuration de la propriété ou d’une holding familiale ;','relocalisation ou changement de juridiction ;','création ou refonte d’un family office ;','transformation numérique ou IA majeure ;','décisions présentant une exposition réglementaire, réputationnelle ou conflictuelle familiale importante.']},
      {heading:'Perspective Decision Security',paragraphs:['La question centrale n’est pas seulement de savoir si une opération est juridiquement possible ou financièrement attractive. Il s’agit de déterminer si la décision reste défendable lorsque ses hypothèses, ses preuves, ses dépendances, ses scénarios alternatifs et ses conditions de mise en œuvre sont examinés ensemble.','TAMVER sépare la vérification indépendante de l’exécution. Les conseils juridiques, fiscaux, d’investissement et de transaction peuvent rester chargés de l’exécution tandis que Decision Security examine la décision avant engagement.']},
      {heading:'Dimensions de recherche',numbered:['Irréversibilité — difficulté et coût d’un retour en arrière.','Exposition du capital — part du patrimoine familial ou de la capacité opérationnelle mise en risque.','Exposition de la gouvernance familiale — branches, générations ou droits de contrôle affectés.','Exposition réglementaire et transfrontalière — dépendance à des conditions fiscales, AML, substance, reporting ou juridictionnelles.','Incitations des conseillers — bénéfice éventuel lié à la réalisation de l’opération.','Exposition réputationnelle et opérationnelle — impact potentiel sur la continuité, la confiance, la position de marché ou les dépendances critiques.']},
      {heading:'Méthodes TAMVER courantes',bullets:['DSS pour la qualité de la décision, les preuves et la préparation à la mise en œuvre ;','AIR pour cartographier les dépendances intersystèmes et intersectorielles ;','Scenario Stress-Test pour tester des futurs alternatifs et des conditions de défaillance ;','SCM pour examiner la résilience de la structure porteuse de la décision ;','Evidence Registry pour séparer faits sourcés, hypothèses, calculs et interprétation experte.']},
      {heading:'Règle de publication',paragraphs:['Cette page définit le cadre de recherche. Les affirmations quantitatives de marché, conclusions juridictionnelles et résultats de cas ne doivent être publiés qu’après rattachement aux preuves et validation par le processus de publication TAMVER.']}
    ]},
    de:{sections:[
      {heading:'Forschungsschwerpunkt',paragraphs:['Dieser Bereich untersucht strategische Entscheidungen in Familienunternehmen anhand der Governance strategischer Entscheidungen, von Interdependenzen und Szenarioresilienz.']},
      {heading:'Warum Familienunternehmen eine eigene Perspektive benötigen',paragraphs:['In einem Familienunternehmen kann eine strategische Entscheidung gleichzeitig Eigentum, operative Kontrolle, Familien-Governance, Nachfolge, Kapitalstruktur, regulatorische Exposition, Reputation und Beziehungen zwischen Familienzweigen beeinflussen. Eine in einer Dimension attraktive Entscheidung kann in einer anderen Fragilität erzeugen.','Decision Security behandelt das Familienunternehmen als verbundenes Entscheidungssystem, in dem geschäftliche und eigentümerbezogene Folgen gemeinsam bewertet werden müssen.']},
      {heading:'Entscheidungen mit hoher Tragweite',bullets:['Nachfolge und Übertragung der Kontrolle;','Verkauf des Unternehmens oder eines wesentlichen Anteils;','Akquisitionen und große Kapitalinvestitionen;','Eintritt in ein neues Land, einen neuen Markt oder regulierten Sektor;','Umstrukturierung von Eigentum oder Familienholding;','Verlagerung oder Wechsel der Jurisdiktion;','Aufbau oder Neugestaltung eines Family Office;','große digitale oder KI-Transformation;','Entscheidungen mit wesentlicher regulatorischer, reputativer oder familienbezogener Konfliktexposition.']},
      {heading:'Decision-Security-Perspektive',paragraphs:['Die Kernfrage ist nicht nur, ob eine Transaktion rechtlich möglich oder finanziell attraktiv ist. Geprüft wird, ob die Entscheidung belastbar bleibt, wenn Annahmen, Evidenz, Abhängigkeiten, alternative Szenarien und Umsetzungsbedingungen gemeinsam betrachtet werden.','TAMVER trennt unabhängige Entscheidungsverifikation von der Ausführung. Rechts-, Steuer-, Investment- und Transaktionsberater können für die Umsetzung verantwortlich bleiben, während Decision Security die Entscheidung vor der Bindung prüft.']},
      {heading:'Forschungsdimensionen',numbered:['Irreversibilität — Schwierigkeit und Kosten einer Rücknahme.','Kapitalexposition — Anteil des Familienvermögens oder der operativen Fähigkeit im Risiko.','Familien-Governance-Exposition — betroffene Familienzweige, Generationen oder Kontrollrechte.','Regulatorische und grenzüberschreitende Exposition — Abhängigkeit von Steuer-, AML-, Substance-, Reporting- oder Jurisdiktionsbedingungen.','Berateranreize — ob an der Ausführung Beteiligte vom Zustandekommen der Transaktion profitieren.','Reputations- und operative Exposition — potenzieller Einfluss auf Kontinuität, Vertrauen, Marktposition oder kritische Abhängigkeiten.']},
      {heading:'Typische TAMVER-Methoden',bullets:['DSS für Entscheidungsqualität, Evidenz und Umsetzungsbereitschaft;','AIR zur Abbildung system- und sektorübergreifender Abhängigkeiten;','Scenario Stress-Test für alternative Zukunftslagen und Ausfallbedingungen;','SCM zur Prüfung der Resilienz der tragenden Struktur;','Evidence Registry zur Trennung von belegten Fakten, Annahmen, Berechnungen und Experteninterpretation.']},
      {heading:'Publikationsregel',paragraphs:['Diese Seite definiert den Forschungsrahmen. Quantitative Marktaussagen, jurisdiktionsbezogene Schlussfolgerungen und Fallbefunde werden nur veröffentlicht, wenn sie mit Evidenz verknüpft und durch den TAMVER-Publikationsprozess freigegeben sind.']}
    ]},
    it:{sections:[
      {heading:'Focus di ricerca',paragraphs:['Quest’area studia le decisioni strategiche nelle imprese familiari attraverso il governo delle decisioni, le interdipendenze e la resilienza agli scenari.']},
      {heading:'Perché l’impresa familiare richiede una prospettiva specifica',paragraphs:['In un’impresa familiare, una decisione strategica può influire contemporaneamente su proprietà, controllo operativo, governo familiare, successione, struttura del capitale, esposizione normativa, reputazione e rapporti tra rami familiari. Una decisione attraente in una dimensione può creare fragilità in un’altra.','Decision Security considera l’impresa familiare come un sistema decisionale connesso nel quale le conseguenze aziendali e proprietarie devono essere valutate insieme.']},
      {heading:'Decisioni ad alto impatto',bullets:['successione e trasferimento del controllo;','vendita dell’impresa o di una quota significativa;','acquisizioni e grandi investimenti di capitale;','ingresso in un nuovo paese, mercato o settore regolamentato;','ristrutturazione della proprietà o della holding familiare;','rilocalizzazione o cambio di giurisdizione;','creazione o riprogettazione di un family office;','grande trasformazione digitale o AI;','decisioni con esposizione normativa, reputazionale o di conflitto familiare rilevante.']},
      {heading:'Prospettiva Decision Security',paragraphs:['La domanda centrale non è solo se un’operazione sia giuridicamente possibile o finanziariamente attraente. Si verifica se la decisione resta difendibile quando ipotesi, evidenze, dipendenze, scenari alternativi e condizioni di implementazione vengono esaminati insieme.','TAMVER separa la verifica indipendente dall’esecuzione. I consulenti legali, fiscali, d’investimento e transazione possono restare responsabili dell’implementazione mentre Decision Security esamina la decisione prima dell’impegno.']},
      {heading:'Dimensioni di ricerca',numbered:['Irreversibilità — difficoltà e costo di annullare la decisione.','Esposizione del capitale — quota del patrimonio familiare o della capacità operativa a rischio.','Esposizione del governo familiare — rami, generazioni o diritti di controllo interessati.','Esposizione normativa e transfrontaliera — dipendenza da condizioni fiscali, AML, substance, reporting o giurisdizionali.','Incentivi dei consulenti — eventuale beneficio derivante dall’esecuzione dell’operazione.','Esposizione reputazionale e operativa — potenziale impatto su continuità, fiducia, posizione di mercato o dipendenze critiche.']},
      {heading:'Metodi TAMVER tipici',bullets:['DSS per qualità della decisione, evidenze e prontezza all’implementazione;','AIR per mappare dipendenze tra sistemi e settori;','Scenario Stress-Test per futuri alternativi e condizioni di fallimento;','SCM per esaminare la resilienza della struttura che deve sostenere la decisione;','Evidence Registry per separare fatti supportati da fonti, ipotesi, calcoli e interpretazione esperta.']},
      {heading:'Regola di pubblicazione',paragraphs:['Questa pagina definisce il quadro di ricerca. Le affermazioni quantitative di mercato, le conclusioni giurisdizionali e i risultati dei casi devono essere pubblicati solo se collegati alle evidenze e approvati attraverso il processo di pubblicazione TAMVER.']}
    ]},
    pt:{sections:[
      {heading:'Foco de investigação',paragraphs:['Esta área estuda decisões estratégicas em empresas familiares através da governação das decisões, das interdependências e da resiliência a cenários.']},
      {heading:'Porque a empresa familiar exige uma perspetiva própria',paragraphs:['Numa empresa familiar, uma decisão estratégica pode afetar simultaneamente propriedade, controlo operacional, governação familiar, sucessão, estrutura de capital, exposição regulatória, reputação e relações entre ramos familiares. Uma decisão atrativa numa dimensão pode criar fragilidade noutra.','Decision Security trata a empresa familiar como um sistema de decisão conectado no qual as consequências empresariais e patrimoniais devem ser avaliadas em conjunto.']},
      {heading:'Decisões de elevado impacto',bullets:['sucessão e transferência de controlo;','venda da empresa ou de uma participação significativa;','aquisições e grandes investimentos de capital;','entrada num novo país, mercado ou setor regulado;','reestruturação da propriedade ou da holding familiar;','relocalização ou mudança de jurisdição;','criação ou reformulação de um family office;','grande transformação digital ou de IA;','decisões com exposição regulatória, reputacional ou de conflito familiar material.']},
      {heading:'Perspetiva Decision Security',paragraphs:['A questão central não é apenas se uma operação é juridicamente possível ou financeiramente atrativa. Analisa-se se a decisão continua defensável quando pressupostos, evidência, dependências, cenários alternativos e condições de implementação são examinados em conjunto.','A TAMVER separa a verificação independente da execução. Os consultores jurídicos, fiscais, de investimento e de transação podem continuar responsáveis pela implementação enquanto Decision Security examina a decisão antes do compromisso.']},
      {heading:'Dimensões de investigação',numbered:['Irreversibilidade — dificuldade e custo de reverter a decisão.','Exposição de capital — parte do património familiar ou da capacidade operacional colocada em risco.','Exposição de governação familiar — ramos, gerações ou direitos de controlo afetados.','Exposição regulatória e transfronteiriça — dependência de condições fiscais, AML, substance, reporting ou de jurisdição.','Incentivos dos consultores — eventual benefício decorrente da execução da operação.','Exposição reputacional e operacional — potencial impacto na continuidade, confiança, posição de mercado ou dependências críticas.']},
      {heading:'Métodos TAMVER habituais',bullets:['DSS para qualidade da decisão, evidência e preparação para a implementação;','AIR para mapear dependências entre sistemas e setores;','Scenario Stress-Test para futuros alternativos e condições de falha;','SCM para examinar a resiliência da estrutura que deve suportar a decisão;','Evidence Registry para separar factos sustentados por fontes, pressupostos, cálculos e interpretação especializada.']},
      {heading:'Regra de publicação',paragraphs:['Esta página define o quadro de investigação. Afirmações quantitativas de mercado, conclusões jurisdicionais e resultados de casos só devem ser publicados quando ligados à evidência e aprovados pelo processo de publicação TAMVER.']}
    ]}
  },

  'strategic-decision-audit': {
    ru:{sections:[
      {heading:'Цель',paragraphs:['Аудит создаёт трассируемое представление о предпосылках, доказательствах, зависимостях и рисках реализации, на которых основано стратегическое решение.']},
      {heading:'Для чего нужен аудит',paragraphs:['Strategic Decision Audit предназначен для решений с высокой ценой ошибки до необратимого или дорогостоящего обязательства. Он не заменяет юридический due diligence, налоговое структурирование, инвестиционный совет или исполнение сделки. Его задача — проверить само решение на достаточную обоснованность, устойчивость и исполнимость.']},
      {heading:'Ключевые вопросы аудита',numbered:['Какое решение фактически принимается? Должны быть определены объект, мандат, горизонт, владелец решения и условия успеха.','Какие предпосылки несут решение? Критические предпосылки отделяются от подтверждённых фактов.','Какие доказательства поддерживают решение? Проверяются качество, трассируемость, актуальность и зоны расхождений.','Какие зависимости могут изменить результат? AIR используется там, где риск распространяется через сектор, стейкхолдеров, ресурсы, регулирование или инфраструктуру.','Выдерживает ли решение альтернативные сценарии? Проверяются существенные шоки, критические точки и условия отказа.','Может ли организация реализовать и управлять решением? До формирования Decision Gate оцениваются готовность, ответственность, мониторинг и способность к адаптации.']},
      {heading:'Стандартная аналитическая последовательность',bullets:['определение решения и его границ;','сбор доказательств и классификация источников;','интервью с владельцами решения и функциональными экспертами;','DSS-оценка зрелости, рисков, уверенности и готовности к реализации;','AIR-карта материальных взаимозависимостей;','Scenario Stress-Test альтернативных условий и критических точек;','экспертная валидация и фиксация пробелов в доказательствах;','Decision Gate и приоритетная дорожная карта.']},
      {heading:'Результаты',bullets:['определение решения и реестр предпосылок;','DSS-оценка и представление Decision Security;','выводы по уверенности доказательств;','карта AIR-критических связей;','результаты сценарного давления и критических точек;','разрывы реализации и управления;','условия Decision Gate;','приоритетные действия и требования мониторинга.']},
      {heading:'Принцип Decision Gate',paragraphs:['Результат не означает устранение риска. Decision Gate фиксирует, может ли решение продолжаться, допустимо ли оно только при явных условиях, требует ли переработки или пока не имеет достаточной доказательной базы для принятия обязательств.']},
      {heading:'Граница независимости',paragraphs:['Роль TAMVER в Decision Security аналитически отделена от советников, чьё вознаграждение может зависеть от исполнения, AUM, продажи продукта или закрытия сделки. Существующие юридические, налоговые, финансовые и операционные советники могут оставаться в процессе, пока само решение проходит независимую проверку.']},
      {heading:'Правило публикации',paragraphs:['Клиентские выводы и количественные результаты остаются непубличными, если не одобрены отдельно. Публичные утверждения должны быть трассируемы к валидированной доказательной базе, а не выводиться автоматически из внутренней оценки.']}
    ]},
    es:{sections:[
      {heading:'Objetivo',paragraphs:['La auditoría crea una visión trazable de los supuestos, la evidencia, las dependencias y los riesgos de implementación que sustentan una decisión estratégica.']},
      {heading:'Para qué sirve',paragraphs:['Strategic Decision Audit está diseñado para decisiones de alto impacto antes de un compromiso irreversible o costoso. No sustituye la due diligence legal, la estructuración fiscal, el asesoramiento de inversión ni la ejecución de una transacción. Su función es comprobar si la propia decisión está suficientemente respaldada, es resiliente y ejecutable.']},
      {heading:'Preguntas centrales',numbered:['¿Qué decisión se está tomando realmente? Deben quedar explícitos objeto, mandato, horizonte, responsable y condiciones de éxito.','¿Qué supuestos sostienen la decisión? Los supuestos críticos se separan de los hechos verificados.','¿Qué evidencia la respalda? Se revisan calidad, trazabilidad, actualidad y áreas de desacuerdo.','¿Qué dependencias pueden cambiar el resultado? AIR se utiliza cuando el riesgo puede propagarse por sectores, partes interesadas, recursos, regulación o infraestructura.','¿Sobrevive la decisión a escenarios alternativos? Se prueban shocks relevantes, puntos críticos y condiciones de fallo.','¿Puede la organización implementarla y gobernarla? Antes del Decision Gate se revisan preparación, responsabilidades, seguimiento y capacidad de adaptación.']},
      {heading:'Secuencia analítica estándar',bullets:['delimitación de la decisión y su alcance;','recopilación de evidencia y clasificación de fuentes;','entrevistas con responsables de decisión y expertos funcionales;','evaluación DSS de madurez, riesgo, confianza y preparación;','mapeo AIR de interdependencias materiales;','Scenario Stress-Test de condiciones alternativas y puntos críticos;','validación experta y registro de brechas de evidencia;','Decision Gate y hoja de ruta priorizada.']},
      {heading:'Resultados',bullets:['definición de la decisión y registro de supuestos;','evaluación DSS y visión Decision Security;','hallazgos sobre confianza de la evidencia;','mapa de enlaces críticos AIR;','hallazgos de presión de escenarios y puntos críticos;','brechas de implementación y gobernanza;','condiciones del Decision Gate;','acciones priorizadas y requisitos de monitorización.']},
      {heading:'Principio Decision Gate',paragraphs:['El resultado no promete que el riesgo haya sido eliminado. Decision Gate registra si la decisión puede continuar, debe continuar solo bajo condiciones explícitas, requiere rediseño o carece de evidencia suficiente para el compromiso.']},
      {heading:'Límite de independencia',paragraphs:['El papel de TAMVER en Decision Security está separado analíticamente de asesores cuya remuneración pueda depender de la ejecución, AUM, colocación de productos o cierre de la operación. Los asesores legales, fiscales, financieros y operativos existentes pueden seguir participando mientras la decisión se somete a una prueba independiente.']},
      {heading:'Regla de publicación',paragraphs:['Los hallazgos específicos del cliente y las conclusiones cuantitativas siguen siendo no públicos salvo aprobación expresa. Las afirmaciones públicas deben ser trazables a evidencia validada y no inferirse automáticamente de una evaluación interna.']}
    ]},
    ca:{sections:[
      {heading:'Objectiu',paragraphs:['L’auditoria crea una visió traçable dels supòsits, l’evidència, les dependències i els riscos d’implementació que sustenten una decisió estratègica.']},
      {heading:'Per a què serveix',paragraphs:['Strategic Decision Audit està dissenyat per a decisions d’alt impacte abans d’un compromís irreversible o costós. No substitueix la due diligence legal, l’estructuració fiscal, l’assessorament d’inversió ni l’execució d’una transacció. La seva funció és comprovar si la decisió està prou sustentada, és resilient i executable.']},
      {heading:'Preguntes centrals',numbered:['Quina decisió s’està prenent realment? Han de quedar explícits objecte, mandat, horitzó, responsable i condicions d’èxit.','Quins supòsits sostenen la decisió? Els supòsits crítics se separen dels fets verificats.','Quina evidència la sustenta? Es revisen qualitat, traçabilitat, actualitat i àrees de desacord.','Quines dependències poden canviar el resultat? AIR s’utilitza quan el risc es pot propagar per sectors, parts interessades, recursos, regulació o infraestructura.','La decisió resisteix escenaris alternatius? Es proven xocs rellevants, punts crítics i condicions de fallada.','L’organització pot implementar-la i governar-la? Abans del Decision Gate es revisen preparació, responsabilitats, seguiment i capacitat d’adaptació.']},
      {heading:'Seqüència analítica estàndard',bullets:['delimitació de la decisió i el seu abast;','recollida d’evidència i classificació de fonts;','entrevistes amb responsables de decisió i experts funcionals;','avaluació DSS de maduresa, risc, confiança i preparació;','mapatge AIR d’interdependències materials;','Scenario Stress-Test de condicions alternatives i punts crítics;','validació experta i registre de buits d’evidència;','Decision Gate i full de ruta prioritzat.']},
      {heading:'Resultats',bullets:['definició de la decisió i registre de supòsits;','avaluació DSS i visió Decision Security;','resultats sobre confiança de l’evidència;','mapa d’enllaços crítics AIR;','resultats de pressió d’escenaris i punts crítics;','buits d’implementació i governança;','condicions del Decision Gate;','accions prioritzades i requisits de monitoratge.']},
      {heading:'Principi Decision Gate',paragraphs:['El resultat no promet que el risc s’hagi eliminat. Decision Gate registra si la decisió pot continuar, només pot continuar sota condicions explícites, requereix redisseny o no disposa d’evidència suficient per al compromís.']},
      {heading:'Límit d’independència',paragraphs:['El paper de TAMVER en Decision Security està separat analíticament dels assessors la remuneració dels quals pugui dependre de l’execució, AUM, col·locació de productes o tancament de l’operació. Els assessors legals, fiscals, financers i operatius existents poden continuar participant mentre la decisió se sotmet a una prova independent.']},
      {heading:'Regla de publicació',paragraphs:['Els resultats específics del client i les conclusions quantitatives continuen sent no públiques llevat d’aprovació expressa. Les afirmacions públiques han de ser traçables a evidència validada i no inferir-se automàticament d’una avaluació interna.']}
    ]},
    fr:{sections:[
      {heading:'Objectif',paragraphs:['L’audit crée une vue traçable des hypothèses, des éléments probants, des dépendances et des risques de mise en œuvre qui soutiennent une décision stratégique.']},
      {heading:'Finalité',paragraphs:['Strategic Decision Audit est conçu pour les décisions à fort enjeu avant un engagement irréversible ou coûteux. Il ne remplace ni la due diligence juridique, ni la structuration fiscale, ni le conseil en investissement, ni l’exécution d’une transaction. Son rôle est de vérifier si la décision elle-même est suffisamment étayée, résiliente et exécutable.']},
      {heading:'Questions centrales',numbered:['Quelle décision est réellement prise ? L’objet, le mandat, l’horizon, le responsable et les conditions de succès doivent être explicites.','Quelles hypothèses portent la décision ? Les hypothèses critiques sont séparées des faits vérifiés.','Quelles preuves la soutiennent ? La qualité, la traçabilité, l’actualité et les zones de désaccord sont examinées.','Quelles dépendances peuvent modifier le résultat ? AIR est utilisé lorsque le risque peut se propager via secteurs, parties prenantes, ressources, réglementation ou infrastructure.','La décision résiste-t-elle à des scénarios alternatifs ? Les chocs matériels, points critiques et conditions de défaillance sont testés.','L’organisation peut-elle mettre en œuvre et gouverner la décision ? Avant le Decision Gate, la préparation, les responsabilités, le suivi et la capacité d’adaptation sont examinés.']},
      {heading:'Séquence analytique standard',bullets:['cadrage de la décision et de son périmètre ;','collecte des preuves et classification des sources ;','entretiens avec les responsables de décision et experts fonctionnels ;','évaluation DSS de maturité, risque, confiance et préparation ;','cartographie AIR des interdépendances matérielles ;','Scenario Stress-Test des conditions alternatives et points critiques ;','validation experte et identification des lacunes de preuve ;','Decision Gate et feuille de route priorisée.']},
      {heading:'Résultats',bullets:['définition de la décision et registre des hypothèses ;','évaluation DSS et vue Decision Security ;','constats sur la confiance dans les preuves ;','carte des liens critiques AIR ;','résultats de pression des scénarios et points critiques ;','lacunes de mise en œuvre et de gouvernance ;','conditions du Decision Gate ;','actions prioritaires et exigences de suivi.']},
      {heading:'Principe Decision Gate',paragraphs:['Le résultat ne promet pas l’élimination du risque. Decision Gate indique si la décision peut avancer, doit avancer uniquement sous conditions explicites, nécessite une refonte ou manque encore de preuves suffisantes pour un engagement.']},
      {heading:'Frontière d’indépendance',paragraphs:['Le rôle TAMVER en Decision Security est analytiquement distinct des conseillers dont la rémunération peut dépendre de l’exécution, des AUM, du placement de produits ou de la réalisation de la transaction. Les conseils existants peuvent rester impliqués pendant que la décision est testée indépendamment.']},
      {heading:'Règle de publication',paragraphs:['Les constats propres au client et les conclusions quantitatives restent non publics sauf approbation explicite. Les affirmations publiques doivent être traçables à des preuves validées et ne pas être déduites automatiquement d’une évaluation interne.']}
    ]},
    de:{sections:[
      {heading:'Ziel',paragraphs:['Das Audit schafft eine nachvollziehbare Sicht auf Annahmen, Evidenz, Abhängigkeiten und Umsetzungsrisiken, die eine strategische Entscheidung tragen.']},
      {heading:'Wofür das Audit dient',paragraphs:['Strategic Decision Audit ist für Entscheidungen mit hoher Tragweite vor einer irreversiblen oder kostspieligen Bindung konzipiert. Es ersetzt weder rechtliche Due Diligence noch Steuerstrukturierung, Investmentberatung oder Transaktionsausführung. Seine Aufgabe ist zu prüfen, ob die Entscheidung selbst ausreichend belegt, resilient und umsetzbar ist.']},
      {heading:'Kernfragen',numbered:['Welche Entscheidung wird tatsächlich getroffen? Gegenstand, Mandat, Zeithorizont, Decision Owner und Erfolgskriterien müssen klar sein.','Welche Annahmen tragen die Entscheidung? Kritische Annahmen werden von verifizierten Fakten getrennt.','Welche Evidenz stützt die Entscheidung? Qualität, Nachvollziehbarkeit, Aktualität und Dissenspunkte werden geprüft.','Welche Abhängigkeiten können das Ergebnis verändern? AIR wird genutzt, wenn sich Risiko über Sektoren, Stakeholder, Ressourcen, Regulierung oder Infrastruktur ausbreiten kann.','Hält die Entscheidung alternativen Szenarien stand? Materielle Schocks, kritische Punkte und Ausfallbedingungen werden getestet.','Kann die Organisation die Entscheidung umsetzen und steuern? Vor dem Decision Gate werden Bereitschaft, Verantwortung, Monitoring und Anpassungsfähigkeit geprüft.']},
      {heading:'Standardmäßige Analysefolge',bullets:['Abgrenzung von Entscheidung und Entscheidungsrahmen;','Evidenzsammlung und Quellenklassifizierung;','Interviews mit Decision Ownern und Fachexperten;','DSS-Bewertung von Reifegrad, Risiko, Konfidenz und Umsetzungsbereitschaft;','AIR-Kartierung materieller Interdependenzen;','Scenario Stress-Test alternativer Bedingungen und kritischer Punkte;','Expertenvalidierung und Erfassung offener Evidenzlücken;','Decision Gate und priorisierte Roadmap.']},
      {heading:'Ergebnisse',bullets:['Entscheidungsdefinition und Annahmenregister;','DSS-Bewertung und Decision-Security-Sicht;','Befunde zur Evidenzkonfidenz;','AIR-Karte kritischer Verbindungen;','Befunde zu Szenariodruck und kritischen Punkten;','Umsetzungs- und Governance-Lücken;','Decision-Gate-Bedingungen;','priorisierte Maßnahmen und Monitoringanforderungen.']},
      {heading:'Decision-Gate-Prinzip',paragraphs:['Das Ergebnis verspricht keine Risikobeseitigung. Decision Gate hält fest, ob die Entscheidung fortgeführt werden kann, nur unter expliziten Bedingungen weitergeführt werden sollte, neu gestaltet werden muss oder noch nicht ausreichend Evidenz für eine Bindung besitzt.']},
      {heading:'Unabhängigkeitsgrenze',paragraphs:['Die TAMVER-Rolle in Decision Security ist analytisch von Beratern getrennt, deren Vergütung von Ausführung, AUM, Produktplatzierung oder Transaktionsabschluss abhängen kann. Bestehende Rechts-, Steuer-, Finanz- und operative Berater können beteiligt bleiben, während die Entscheidung unabhängig geprüft wird.']},
      {heading:'Publikationsregel',paragraphs:['Kundenspezifische Befunde und quantitative Schlussfolgerungen bleiben nicht öffentlich, sofern sie nicht ausdrücklich freigegeben sind. Öffentliche Aussagen müssen auf validierte Evidenz zurückführbar sein und dürfen nicht automatisch aus einer internen Bewertung abgeleitet werden.']}
    ]},
    it:{sections:[
      {heading:'Obiettivo',paragraphs:['L’audit crea una visione tracciabile delle ipotesi, delle evidenze, delle dipendenze e dei rischi di implementazione che sostengono una decisione strategica.']},
      {heading:'A cosa serve',paragraphs:['Strategic Decision Audit è pensato per decisioni ad alto impatto prima di un impegno irreversibile o costoso. Non sostituisce due diligence legale, strutturazione fiscale, consulenza d’investimento o esecuzione della transazione. Il suo ruolo è verificare se la decisione stessa sia sufficientemente supportata, resiliente ed eseguibile.']},
      {heading:'Domande centrali',numbered:['Quale decisione viene realmente presa? Oggetto, mandato, orizzonte, responsabile e condizioni di successo devono essere espliciti.','Quali ipotesi sostengono la decisione? Le ipotesi critiche vengono separate dai fatti verificati.','Quali evidenze la supportano? Si esaminano qualità, tracciabilità, attualità e aree di disaccordo.','Quali dipendenze possono cambiare il risultato? AIR viene utilizzato quando il rischio può propagarsi attraverso settori, stakeholder, risorse, regolamentazione o infrastrutture.','La decisione resiste a scenari alternativi? Si testano shock materiali, punti critici e condizioni di fallimento.','L’organizzazione può implementarla e governarla? Prima del Decision Gate si esaminano preparazione, responsabilità, monitoraggio e capacità di adattamento.']},
      {heading:'Sequenza analitica standard',bullets:['definizione della decisione e del suo perimetro;','raccolta delle evidenze e classificazione delle fonti;','interviste con responsabili della decisione ed esperti funzionali;','valutazione DSS di maturità, rischio, fiducia e prontezza;','mappatura AIR delle interdipendenze materiali;','Scenario Stress-Test di condizioni alternative e punti critici;','validazione esperta e registrazione delle lacune di evidenza;','Decision Gate e roadmap prioritaria.']},
      {heading:'Output',bullets:['definizione della decisione e registro delle ipotesi;','valutazione DSS e vista Decision Security;','risultati sulla fiducia nelle evidenze;','mappa AIR dei collegamenti critici;','risultati sulla pressione degli scenari e punti critici;','lacune di implementazione e governo;','condizioni del Decision Gate;','azioni prioritarie e requisiti di monitoraggio.']},
      {heading:'Principio Decision Gate',paragraphs:['L’output non promette l’eliminazione del rischio. Decision Gate registra se la decisione può procedere, deve procedere solo a condizioni esplicite, richiede riprogettazione o non dispone ancora di evidenze sufficienti per l’impegno.']},
      {heading:'Confine di indipendenza',paragraphs:['Il ruolo di TAMVER in Decision Security è analiticamente separato dai consulenti la cui remunerazione può dipendere dall’esecuzione, dall’AUM, dal collocamento di prodotti o dal completamento della transazione. I consulenti esistenti possono restare coinvolti mentre la decisione viene sottoposta a verifica indipendente.']},
      {heading:'Regola di pubblicazione',paragraphs:['I risultati specifici del cliente e le conclusioni quantitative restano non pubblici salvo approvazione esplicita. Le affermazioni pubbliche devono essere tracciabili a evidenze validate e non dedotte automaticamente da una valutazione interna.']}
    ]},
    pt:{sections:[
      {heading:'Objetivo',paragraphs:['A auditoria cria uma visão rastreável dos pressupostos, da evidência, das dependências e dos riscos de implementação que sustentam uma decisão estratégica.']},
      {heading:'Para que serve',paragraphs:['Strategic Decision Audit destina-se a decisões de elevado impacto antes de um compromisso irreversível ou dispendioso. Não substitui due diligence jurídica, estruturação fiscal, aconselhamento de investimento ou execução da transação. A sua função é testar se a própria decisão está suficientemente suportada, é resiliente e executável.']},
      {heading:'Questões centrais',numbered:['Que decisão está realmente a ser tomada? Objeto, mandato, horizonte, responsável e condições de sucesso devem ser explícitos.','Que pressupostos sustentam a decisão? Os pressupostos críticos são separados dos factos verificados.','Que evidência a suporta? Revêem-se qualidade, rastreabilidade, atualidade e áreas de desacordo.','Que dependências podem alterar o resultado? AIR é utilizado quando o risco pode propagar-se por setores, stakeholders, recursos, regulação ou infraestrutura.','A decisão resiste a cenários alternativos? Testam-se choques materiais, pontos críticos e condições de falha.','A organização consegue implementá-la e governá-la? Antes do Decision Gate revêem-se preparação, responsabilidades, monitorização e capacidade de adaptação.']},
      {heading:'Sequência analítica padrão',bullets:['delimitação da decisão e do seu âmbito;','recolha de evidência e classificação de fontes;','entrevistas com responsáveis pela decisão e especialistas funcionais;','avaliação DSS de maturidade, risco, confiança e preparação;','mapeamento AIR de interdependências materiais;','Scenario Stress-Test de condições alternativas e pontos críticos;','validação especializada e registo de lacunas de evidência;','Decision Gate e roteiro priorizado.']},
      {heading:'Resultados',bullets:['definição da decisão e registo de pressupostos;','avaliação DSS e visão Decision Security;','resultados sobre confiança da evidência;','mapa AIR de ligações críticas;','resultados de pressão de cenários e pontos críticos;','lacunas de implementação e governação;','condições do Decision Gate;','ações prioritárias e requisitos de monitorização.']},
      {heading:'Princípio Decision Gate',paragraphs:['O resultado não promete eliminação do risco. Decision Gate regista se a decisão pode avançar, deve avançar apenas sob condições explícitas, exige reformulação ou ainda não possui evidência suficiente para o compromisso.']},
      {heading:'Limite de independência',paragraphs:['O papel da TAMVER em Decision Security está analiticamente separado de consultores cuja remuneração possa depender da execução, AUM, colocação de produtos ou conclusão da transação. Os consultores jurídicos, fiscais, financeiros e operacionais existentes podem permanecer envolvidos enquanto a decisão é testada de forma independente.']},
      {heading:'Regra de publicação',paragraphs:['Os resultados específicos do cliente e as conclusões quantitativas permanecem não públicos salvo aprovação explícita. As afirmações públicas devem ser rastreáveis a evidência validada e não inferidas automaticamente de uma avaliação interna.']}
    ]}
  },

  'decision-security-research-program': {
    ru:{sections:[
      {heading:'Исследовательская программа',paragraphs:['Программа развивает концепции, методы и сравнительные исследования в области устойчивости стратегических решений.']},
      {heading:'Назначение',paragraphs:['Decision Security Research Program формирует аналитическую основу для проверки того, являются ли стратегические решения с высокой ценой ошибки доказательными, устойчивыми, исполнимыми и управляемыми до принятия обязательств. Программа не ограничивается одним сектором и охватывает государства, семейный бизнес, институты, инвестиционные программы, инфраструктуру и сложные корпоративные среды.']},
      {heading:'Ключевые исследовательские домены',numbered:['Качество решений — как решения формулируются, управляются и проверяются до обязательства.','Качество доказательств — как сила источника, трассируемость, актуальность, неопределённость и экспертные расхождения влияют на уверенность.','Взаимозависимости — как секторные, стейкхолдерские, ресурсные, регуляторные и технологические связи распространяют риск и возможности.','Сценарная устойчивость — как решение ведёт себя при альтернативных будущих условиях, шоках, критических точках и изменении предпосылок.','Структурная устойчивость — имеет ли организация, система или юрисдикция достаточную операционную, институциональную и ресурсную способность для реализации решения.']},
      {heading:'Методологическая архитектура',bullets:['DSS — базовая рамка оценки Decision Security;','AIR — взаимозависимости, каскадные эффекты, критические точки и пути возможностей;','SCM — структурная устойчивость по ключевым измерениям безопасности;','Scenario Stress-Test — альтернативные условия и пути отказа;','Evidence Registry — разделение подтверждённых фактов, предпосылок, расчётов и экспертной интерпретации.']},
      {heading:'Исследовательские результаты',bullets:['методологические документы и контролируемые определения;','отраслевые и страновые исследования;','сравнительные исследования Decision Security;','кейсы с доказательной базой;','разработка бенчмарков;','библиотеки сценариев и рамки раннего предупреждения;','публичные исследовательские брифы и executive reports;','развитие инструментов оценки и цифровых аналитических средств.']},
      {heading:'Правило доказательств и происхождения',paragraphs:['Research layer не создаёт параллельную систему доказательств. Публичные аналитические утверждения должны оставаться трассируемыми через архитектуру доказательств TAMVER. VALIDATED не означает автоматически PUBLIC: доказательства, метрики и claims проходят отдельные публикационные контроли.']},
      {heading:'Исследовательская дисциплина',bullets:['подтверждённые внешние факты;','внутренние предпосылки и модельные входы;','расчётные результаты;','экспертная интерпретация.'],paragraphs:['Эти четыре объекта не должны смешиваться: необходимо сохранять различие между тем, что известно, что моделируется и что интерпретируется.']},
      {heading:'Направление развития',paragraphs:['Долгосрочная цель — превратить накопленные исследования, валидированные доказательства, сценарный анализ и сравнительные кейсы в повторно используемую систему знаний Decision Security, поддерживающую как экспертную работу, так и цифровые инструменты принятия решений без ослабления provenance и публикационных контролей.']}
    ]},
    es:{sections:[
      {heading:'Agenda de investigación',paragraphs:['El programa desarrolla conceptos, métodos e investigación comparativa sobre la resiliencia de las decisiones estratégicas.']},
      {heading:'Propósito',paragraphs:['Decision Security Research Program desarrolla la base analítica para examinar si decisiones estratégicas de alto impacto están respaldadas por evidencia, son resilientes, ejecutables y gobernables antes del compromiso. No se limita a un sector: estudia gobiernos, empresas familiares, instituciones, programas de inversión, infraestructura y entornos corporativos complejos.']},
      {heading:'Dominios centrales',numbered:['Calidad de decisión — cómo se formulan, gobiernan y prueban las decisiones antes del compromiso.','Calidad de evidencia — cómo fuerza de fuente, trazabilidad, actualidad, incertidumbre y desacuerdo experto afectan a la confianza.','Interdependencias — cómo relaciones sectoriales, de stakeholders, recursos, regulación y tecnología propagan riesgo y oportunidad.','Resiliencia de escenarios — cómo se comporta una decisión bajo futuros alternativos, shocks, puntos críticos y cambios de supuestos.','Resiliencia estructural — si la organización, sistema o jurisdicción posee suficiente capacidad operativa, institucional y de recursos para sostener la decisión.']},
      {heading:'Arquitectura metodológica',bullets:['DSS como marco central de evaluación Decision Security;','AIR para interdependencias, efectos en cascada, puntos críticos y vías de oportunidad;','SCM para resiliencia estructural;','Scenario Stress-Test para condiciones alternativas y rutas de fallo;','Evidence Registry para separar hechos respaldados por fuentes, supuestos, cálculos e interpretación experta.']},
      {heading:'Resultados de investigación',bullets:['documentos metodológicos y definiciones controladas;','investigación sectorial y de países;','estudios comparativos de Decision Security;','análisis de casos respaldados por evidencia;','desarrollo de benchmarks;','bibliotecas de escenarios y marcos de alerta temprana;','briefs públicos y executive reports;','refinamiento de instrumentos de evaluación y herramientas digitales.']},
      {heading:'Regla de evidencia y procedencia',paragraphs:['La capa Research no crea un sistema paralelo de evidencia. Las afirmaciones analíticas públicas deben seguir siendo trazables mediante la arquitectura de evidencia TAMVER. VALIDATED no equivale automáticamente a PUBLIC: evidencia, métricas y claims deben superar controles de publicación.']},
      {heading:'Disciplina de investigación',bullets:['hechos externos verificados;','supuestos internos y entradas de modelo;','resultados calculados;','interpretación experta.'],paragraphs:['Estos cuatro objetos no deben colapsarse entre sí. La separación preserva la diferencia entre lo conocido, lo modelado y lo concluido.']},
      {heading:'Dirección de desarrollo',paragraphs:['El objetivo a largo plazo es convertir investigación acumulada, evidencia validada, análisis de escenarios y casos comparativos en un sistema reutilizable de conocimiento Decision Security que apoye tanto la revisión humana como herramientas digitales sin debilitar la procedencia ni los controles de publicación.']}
    ]},
    ca:{sections:[
      {heading:'Agenda de recerca',paragraphs:['El programa desenvolupa conceptes, mètodes i recerca comparativa sobre la resiliència de les decisions estratègiques.']},
      {heading:'Propòsit',paragraphs:['Decision Security Research Program desenvolupa la base analítica per examinar si decisions estratègiques d’alt impacte estan sustentades per evidència, són resilients, executables i governables abans del compromís. No es limita a un sector: estudia governs, empreses familiars, institucions, programes d’inversió, infraestructura i entorns corporatius complexos.']},
      {heading:'Dominis centrals',numbered:['Qualitat de decisió — com es formulen, governen i proven les decisions abans del compromís.','Qualitat de l’evidència — com la força de la font, la traçabilitat, l’actualitat, la incertesa i el desacord expert afecten la confiança.','Interdependències — com les relacions sectorials, de stakeholders, recursos, regulació i tecnologia propaguen risc i oportunitat.','Resiliència d’escenaris — com es comporta una decisió sota futurs alternatius, xocs, punts crítics i canvis de supòsits.','Resiliència estructural — si l’organització, sistema o jurisdicció disposa de capacitat operativa, institucional i de recursos suficient per sostenir la decisió.']},
      {heading:'Arquitectura metodològica',bullets:['DSS com a marc central d’avaluació Decision Security;','AIR per a interdependències, efectes en cascada, punts crítics i vies d’oportunitat;','SCM per a resiliència estructural;','Scenario Stress-Test per a condicions alternatives i rutes de fallada;','Evidence Registry per separar fets sustentats per fonts, supòsits, càlculs i interpretació experta.']},
      {heading:'Resultats de recerca',bullets:['documents metodològics i definicions controlades;','recerca sectorial i de països;','estudis comparatius de Decision Security;','anàlisis de casos sustentats per evidència;','desenvolupament de benchmarks;','biblioteques d’escenaris i marcs d’alerta primerenca;','briefs públics i executive reports;','refinament d’instruments d’avaluació i eines digitals.']},
      {heading:'Regla d’evidència i procedència',paragraphs:['La capa Research no crea un sistema paral·lel d’evidència. Les afirmacions analítiques públiques han de continuar sent traçables mitjançant l’arquitectura d’evidència TAMVER. VALIDATED no equival automàticament a PUBLIC: evidència, mètriques i claims han de superar controls de publicació.']},
      {heading:'Disciplina de recerca',bullets:['fets externs verificats;','supòsits interns i entrades de model;','resultats calculats;','interpretació experta.'],paragraphs:['Aquests quatre objectes no s’han de confondre. La separació preserva la diferència entre allò conegut, allò modelat i allò conclòs.']},
      {heading:'Direcció de desenvolupament',paragraphs:['L’objectiu a llarg termini és convertir la recerca acumulada, l’evidència validada, l’anàlisi d’escenaris i els casos comparatius en un sistema reutilitzable de coneixement Decision Security que doni suport tant a la revisió humana com a eines digitals sense afeblir la procedència ni els controls de publicació.']}
    ]},
    fr:{sections:[
      {heading:'Programme de recherche',paragraphs:['Le programme développe des concepts, des méthodes et des recherches comparatives sur la résilience des décisions stratégiques.']},
      {heading:'Objectif',paragraphs:['Decision Security Research Program développe la base analytique permettant d’examiner si des décisions stratégiques à fort enjeu sont étayées par des preuves, résilientes, exécutables et gouvernables avant engagement. Le programme couvre gouvernements, entreprises familiales, institutions, programmes d’investissement, infrastructures et environnements d’entreprise complexes.']},
      {heading:'Domaines centraux',numbered:['Qualité de décision — manière dont les décisions sont formulées, gouvernées et testées avant engagement.','Qualité des preuves — influence de la force des sources, de la traçabilité, de l’actualité, de l’incertitude et du désaccord expert sur la confiance.','Interdépendances — propagation du risque et des opportunités par les relations sectorielles, parties prenantes, ressources, réglementation et technologie.','Résilience aux scénarios — comportement d’une décision sous futurs alternatifs, chocs, points critiques et changements d’hypothèses.','Résilience structurelle — capacité opérationnelle, institutionnelle et en ressources de l’organisation, du système ou de la juridiction à porter la décision.']},
      {heading:'Architecture méthodologique',bullets:['DSS comme cadre central d’évaluation Decision Security ;','AIR pour les interdépendances, effets en cascade, points critiques et voies d’opportunité ;','SCM pour la résilience structurelle ;','Scenario Stress-Test pour les conditions alternatives et voies de défaillance ;','Evidence Registry pour séparer faits sourcés, hypothèses, calculs et interprétation experte.']},
      {heading:'Productions de recherche',bullets:['documents méthodologiques et définitions contrôlées ;','recherches sectorielles et pays ;','études comparatives de Decision Security ;','analyses de cas étayées par les preuves ;','développement de benchmarks ;','bibliothèques de scénarios et cadres d’alerte précoce ;','briefs publics et executive reports ;','amélioration des instruments d’évaluation et outils analytiques numériques.']},
      {heading:'Règle de preuve et de provenance',paragraphs:['La couche Research ne crée pas de système de preuve parallèle. Les affirmations analytiques publiques doivent rester traçables dans l’architecture de preuve TAMVER. VALIDATED ne signifie pas automatiquement PUBLIC : preuves, métriques et claims doivent passer les contrôles de publication.']},
      {heading:'Discipline de recherche',bullets:['faits externes vérifiés ;','hypothèses internes et entrées de modèle ;','résultats calculés ;','interprétation experte.'],paragraphs:['Ces quatre objets ne doivent pas être confondus. Cette séparation préserve la différence entre ce qui est connu, modélisé et conclu.']},
      {heading:'Orientation de développement',paragraphs:['L’objectif à long terme est de transformer les recherches accumulées, les preuves validées, l’analyse de scénarios et les cas comparatifs en un système réutilisable de connaissances Decision Security, utilisable par les experts et par des outils numériques sans affaiblir la provenance ni les contrôles de publication.']}
    ]},
    de:{sections:[
      {heading:'Forschungsagenda',paragraphs:['Das Programm entwickelt Konzepte, Methoden und vergleichende Forschung zur Resilienz strategischer Entscheidungen.']},
      {heading:'Zweck',paragraphs:['Decision Security Research Program entwickelt die analytische Grundlage zur Prüfung, ob strategische Entscheidungen mit hoher Tragweite vor einer Bindung evidenzbasiert, resilient, umsetzbar und steuerbar sind. Das Programm umfasst Regierungen, Familienunternehmen, Institutionen, Investitionsprogramme, Infrastruktur und komplexe Unternehmensumfelder.']},
      {heading:'Zentrale Forschungsdomänen',numbered:['Entscheidungsqualität — wie Entscheidungen vor einer Bindung formuliert, gesteuert und getestet werden.','Evidenzqualität — wie Quellenstärke, Nachvollziehbarkeit, Aktualität, Unsicherheit und Expertenabweichungen die Konfidenz beeinflussen.','Interdependenzen — wie sektorale, Stakeholder-, Ressourcen-, regulatorische und technologische Beziehungen Risiko und Chancen übertragen.','Szenarioresilienz — wie sich eine Entscheidung unter alternativen Zukunftslagen, Schocks, kritischen Punkten und veränderten Annahmen verhält.','Strukturelle Resilienz — ob Organisation, System oder Jurisdiktion über ausreichende operative, institutionelle und Ressourcenfähigkeit verfügt.']},
      {heading:'Methodische Architektur',bullets:['DSS als zentraler Decision-Security-Bewertungsrahmen;','AIR für Interdependenzen, Kaskadeneffekte, kritische Punkte und Chancenpfade;','SCM für strukturelle Resilienz;','Scenario Stress-Test für alternative Bedingungen und Ausfallpfade;','Evidence Registry zur Trennung von belegten Fakten, Annahmen, Berechnungen und Experteninterpretation.']},
      {heading:'Forschungsergebnisse',bullets:['Methodikpapiere und kontrollierte Definitionen;','Sektor- und Länderforschung;','vergleichende Decision-Security-Studien;','evidenzbasierte Fallanalysen;','Benchmark-Entwicklung;','Szenariobibliotheken und Frühwarnrahmen;','öffentliche Research Briefs und Executive Reports;','Weiterentwicklung von Bewertungsinstrumenten und digitalen Analysewerkzeugen.']},
      {heading:'Evidenz- und Provenienzregel',paragraphs:['Die Research-Schicht erzeugt kein paralleles Evidenzsystem. Öffentliche analytische Aussagen müssen über die TAMVER-Evidenzarchitektur nachvollziehbar bleiben. VALIDATED bedeutet nicht automatisch PUBLIC: Evidenz, Metriken und Claims müssen die Publikationskontrollen durchlaufen.']},
      {heading:'Forschungsdisziplin',bullets:['verifizierte externe Fakten;','interne Annahmen und Modelleingaben;','berechnete Ergebnisse;','Experteninterpretation.'],paragraphs:['Diese vier Objekte dürfen nicht zusammenfallen. Die Trennung bewahrt den Unterschied zwischen Bekanntem, Modelliertem und Schlussfolgerungen.']},
      {heading:'Entwicklungsrichtung',paragraphs:['Langfristiges Ziel ist, akkumulierte Forschung, validierte Evidenz, Szenarioanalyse und Vergleichsfälle in ein wiederverwendbares Decision-Security-Wissenssystem zu überführen, das menschliche Prüfung und digitale Entscheidungstools unterstützt, ohne Provenienz oder Publikationskontrollen zu schwächen.']}
    ]},
    it:{sections:[
      {heading:'Agenda di ricerca',paragraphs:['Il programma sviluppa concetti, metodi e ricerca comparativa sulla resilienza delle decisioni strategiche.']},
      {heading:'Scopo',paragraphs:['Decision Security Research Program sviluppa la base analitica per esaminare se decisioni strategiche ad alto impatto siano supportate da evidenze, resilienti, eseguibili e governabili prima dell’impegno. Il programma copre governi, imprese familiari, istituzioni, programmi di investimento, infrastrutture e ambienti aziendali complessi.']},
      {heading:'Domini centrali',numbered:['Qualità della decisione — come le decisioni vengono formulate, governate e testate prima dell’impegno.','Qualità delle evidenze — come forza della fonte, tracciabilità, attualità, incertezza e disaccordo esperto influenzano la fiducia.','Interdipendenze — come relazioni settoriali, stakeholder, risorse, regolamentazione e tecnologia propagano rischio e opportunità.','Resilienza agli scenari — comportamento della decisione sotto futuri alternativi, shock, punti critici e cambiamenti delle ipotesi.','Resilienza strutturale — se organizzazione, sistema o giurisdizione dispongono di sufficiente capacità operativa, istituzionale e di risorse.']},
      {heading:'Architettura metodologica',bullets:['DSS come quadro centrale di valutazione Decision Security;','AIR per interdipendenze, effetti a cascata, punti critici e percorsi di opportunità;','SCM per la resilienza strutturale;','Scenario Stress-Test per condizioni alternative e percorsi di fallimento;','Evidence Registry per separare fatti supportati da fonti, ipotesi, calcoli e interpretazione esperta.']},
      {heading:'Output di ricerca',bullets:['documenti metodologici e definizioni controllate;','ricerca settoriale e nazionale;','studi comparativi di Decision Security;','analisi di casi supportate da evidenze;','sviluppo di benchmark;','librerie di scenari e quadri di allerta precoce;','brief pubblici ed executive reports;','perfezionamento di strumenti di valutazione e strumenti digitali.']},
      {heading:'Regola di evidenza e provenienza',paragraphs:['Il livello Research non crea un sistema parallelo di evidenze. Le affermazioni analitiche pubbliche devono restare tracciabili attraverso l’architettura di evidenza TAMVER. VALIDATED non significa automaticamente PUBLIC: evidenze, metriche e claims devono superare i controlli di pubblicazione.']},
      {heading:'Disciplina di ricerca',bullets:['fatti esterni verificati;','ipotesi interne e input del modello;','risultati calcolati;','interpretazione esperta.'],paragraphs:['Questi quattro oggetti non devono essere confusi. La separazione preserva la differenza tra ciò che è noto, modellato e concluso.']},
      {heading:'Direzione di sviluppo',paragraphs:['L’obiettivo a lungo termine è trasformare ricerca accumulata, evidenze validate, analisi degli scenari e casi comparativi in un sistema riutilizzabile di conoscenza Decision Security che supporti revisione umana e strumenti digitali senza indebolire provenienza o controlli di pubblicazione.']}
    ]},
    pt:{sections:[
      {heading:'Agenda de investigação',paragraphs:['O programa desenvolve conceitos, métodos e investigação comparativa sobre a resiliência das decisões estratégicas.']},
      {heading:'Objetivo',paragraphs:['Decision Security Research Program desenvolve a base analítica para examinar se decisões estratégicas de elevado impacto são sustentadas por evidência, resilientes, executáveis e governáveis antes do compromisso. O programa abrange governos, empresas familiares, instituições, programas de investimento, infraestrutura e ambientes empresariais complexos.']},
      {heading:'Domínios centrais',numbered:['Qualidade da decisão — como as decisões são formuladas, governadas e testadas antes do compromisso.','Qualidade da evidência — como força da fonte, rastreabilidade, atualidade, incerteza e desacordo especializado afetam a confiança.','Interdependências — como relações setoriais, stakeholders, recursos, regulação e tecnologia propagam risco e oportunidade.','Resiliência a cenários — como a decisão se comporta sob futuros alternativos, choques, pontos críticos e mudanças de pressupostos.','Resiliência estrutural — se a organização, sistema ou jurisdição possui capacidade operacional, institucional e de recursos suficiente.']},
      {heading:'Arquitetura metodológica',bullets:['DSS como quadro central de avaliação Decision Security;','AIR para interdependências, efeitos em cascata, pontos críticos e vias de oportunidade;','SCM para resiliência estrutural;','Scenario Stress-Test para condições alternativas e caminhos de falha;','Evidence Registry para separar factos sustentados por fontes, pressupostos, cálculos e interpretação especializada.']},
      {heading:'Resultados de investigação',bullets:['documentos metodológicos e definições controladas;','investigação setorial e de países;','estudos comparativos de Decision Security;','análises de casos sustentadas por evidência;','desenvolvimento de benchmarks;','bibliotecas de cenários e quadros de alerta precoce;','briefs públicos e executive reports;','aperfeiçoamento de instrumentos de avaliação e ferramentas digitais.']},
      {heading:'Regra de evidência e proveniência',paragraphs:['A camada Research não cria um sistema paralelo de evidência. As afirmações analíticas públicas devem continuar rastreáveis através da arquitetura de evidência TAMVER. VALIDATED não significa automaticamente PUBLIC: evidência, métricas e claims devem passar pelos controlos de publicação.']},
      {heading:'Disciplina de investigação',bullets:['factos externos verificados;','pressupostos internos e inputs do modelo;','resultados calculados;','interpretação especializada.'],paragraphs:['Estes quatro objetos não devem ser confundidos. A separação preserva a diferença entre o que é conhecido, modelado e concluído.']},
      {heading:'Direção de desenvolvimento',paragraphs:['O objetivo de longo prazo é transformar investigação acumulada, evidência validada, análise de cenários e casos comparativos num sistema reutilizável de conhecimento Decision Security que suporte revisão humana e ferramentas digitais sem enfraquecer proveniência ou controlos de publicação.']}
    ]}
  }
};

export function getResearchKnowledgeArticle(id: string, lang: Lang): MethodologyArticle | null {
  if (lang === 'en') return null;
  return researchKnowledgeContent[id]?.[lang] ?? null;
}
